### ISSUE TITLE
http 500 using build_wwpn_pair

### ISSUE THREAD

**Issue by tpeponas** [powervm/pypowervm#10]
Hello ,

I get an http 500 error usin the function build_wwpn_pair of pypowervm.tasks.vfc_mapper module.
It seems GetNextWWPNs operation is not permiited : 
pypowervm.exceptions.HttpError: HTTP error 500 for method GET on path /rest/api/uom/ManagedSystem/a1b17e97-035b-340f-bbbd-92ed1870c7d0/do/GetNextWWPNs: Internal Server Error -- com.ibm.pmc.rest.servlet.uom.phyp.internal.operations.uom.ManagedSystemGetNextWWPNs

Any help appreciated.

Regards
Thomas.

**Comment by edmondsw** [comment]
This appears to be an underlying issue with NovaLink or VIOS rather than a pypowervm bug. Please open a PMR with IBM support.

**Comment by edmondsw** [comment]
I did ask a NovaLink developer and here's their response:

"If it's KVM then we don't support this operation yet. If it's PowerVM then it we should be getting the value directly from PHYP so I don't see why it would fail, will need logs."

**Comment by tpeponas** [comment]
Ok thanks for the response.
