### ISSUE TITLE
uncap networkx

### ISSUE THREAD

**Issue by prometheanfire** [powervm/pypowervm#4]
any chance you can uncap networkx?  Openstack would like to update this package some time.

https://bugs.launchpad.net/openstack-requirements/+bug/1718576

**Comment by edmondsw** [comment]
That cap was added here: https://github.com/powervm/pypowervm/commit/a7ccb6eb012

pypowervm doesn't use networkx itself, but it depends on taskflow, which does. And taskflow doesn't work with networkx 2.0, which was breaking pypowervm UT. The correct place to put the cap is in taskflow, and that was done starting with taskflow 2.16.0, but openstack currently has the taskflow req set to >=2.7.0, so if anything from 2.7.0 to 2.15.0 is used pypowervm is broken. We will happily uncap networkx once openstack bumps the req for taskflow to >=2.16.0 or higher.

**Comment by edmondsw** [comment]
I proposed such a bump here: https://review.openstack.org/#/c/533751/

**Comment by edmondsw** [comment]
@prometheanfire the networkx requirement has been removed with https://github.com/powervm/pypowervm/commit/016112922a854de2291bade699e20acd91bba05b. Let us know if you need us to cut a release just to get you this or if it'll keep until we would normally spin again.

**Comment by prometheanfire** [comment]
a release would be needed so we can consume it, thanks

**Comment by edmondsw** [comment]
@prometheanfire this is fixed in 1.1.11
