### ISSUE TITLE
Linked clone pypowervm.tasks.storage.crt_lu usage example

### ISSUE THREAD

**Issue by k3it** [powervm/pypowervm#8]
I'd like to create a linked clone LU pointing to one of the existing SSP snapshots (created with the snapshot -create powervm command).  

Can this be done with the `pypowervm.tasks.storage.crt_lu`? 
or can you point to any user space tools or a basic example on how to do it via the powervm API calls?

(I've also posted on the powervm forum at developerworks and created a PMR. apologize for a possible cross-posting)

**Comment by 2uasimojo** [comment]
Yes.  You would specify thin=True, typ=LUType.DISK, and pass the LU or LUEnt wrapper representing the snapshot LU to the `clone` kwarg.  Here's how we do it in OpenStack Nova:

https://github.com/openstack/nova/blob/ceac5d54695dfe64bdf690775ba7c41e250bfa3e/nova/virt/powervm/disk/ssp.py#L202-L204

**Comment by k3it** [comment]
Hi @2uasimojo 

I see, that is part of the python-nova rpm installed with the PowerVC.  I will try to figure out how to call create_disk_from_image  from the shell on the powervc  LPAR.

 'lu -create -clone' flag in some future powervm release would be really useful as well
(i.e get access to the snapshot content  without having to do a rollback).

thanks a lot for the info!
